(define (problem zeno-04-3) (:domain dominio2)
(:customization
(= :time-format "%d/%m/%Y %H:%M:%S")
(= :time-horizon-relative 2500)
(= :time-start "05/06/2007 08:00:00")
(= :time-unit :hours))

(:objects 
    p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 - person
    p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 - person
    Almeria Barcelona Bilbao Cadiz Cordoba Gibraltar - city
    Granada Huelva Jaen Madrid Malaga Sevilla - city
    a1 a2 a3 - aircraft
)
(:init

    (at p1 Barcelona) 
    (at p2 Barcelona)
    (at p3 Barcelona) 
    (at p4 Madrid)
    (at p5 Gibraltar)
    (at p6 Sevilla)
    (at p7 Malaga)
    (at p8 Malaga)
    (at p9 Granada)
    (at p10 Bilbao)
    (at p11 Bilbao)
    (at p12 Bilbao)
    (at p13 Bilbao)
    (at p14 Huelva)
    (at p15 Huelva)
    (at p16 Sevilla)
    (at p17 Malaga)
    (at p18 Almeria)
    (at p19 Almeria)
    (at p20 Cordoba)
    (at p21 Granada)
    (at p22 Cordoba)

    (at a1 Barcelona)
    (at a2 Granada)
    (at a3 Sevilla)

    (= (distance Almeria Sevilla) 410)
    (= (distance Almeria Malaga) 207)
    (= (distance Almeria Madrid) 547)
    (= (distance Almeria Jaen) 220)
    (= (distance Almeria Huelva) 505)
    (= (distance Almeria Granada) 162)
    (= (distance Almeria Gibraltar) 339)
    (= (distance Almeria Cordoba) 316)
    (= (distance Almeria Cadiz) 463)
    (= (distance Almeria Bilbao) 958)
    (= (distance Almeria Barcelona) 809)
    (= (distance Almeria Almeria) 0)

    (= (distance Barcelona Sevilla) 1046)
    (= (distance Barcelona Malaga) 997)
    (= (distance Barcelona Madrid) 621)
    (= (distance Barcelona Jaen) 804)
    (= (distance Barcelona Huelva) 1140)
    (= (distance Barcelona Granada) 868)
    (= (distance Barcelona Gibraltar) 1124)
    (= (distance Barcelona Cordoba) 908)
    (= (distance Barcelona Cadiz) 1284)
    (= (distance Barcelona Bilbao) 620)
    (= (distance Barcelona Almeria) 809)
    (= (distance Barcelona Barcelona) 0)

    (= (distance Bilbao Sevilla) 933)
    (= (distance Bilbao Malaga) 939)
    (= (distance Bilbao Madrid) 395)
    (= (distance Bilbao Jaen) 730)
    (= (distance Bilbao Huelva) 939)
    (= (distance Bilbao Granada) 829)
    (= (distance Bilbao Gibraltar) 1110)
    (= (distance Bilbao Cordoba) 796)
    (= (distance Bilbao Cadiz) 1058)
    (= (distance Bilbao Almeria) 958)
    (= (distance Bilbao Barcelona) 620)
    (= (distance Bilbao Bilbao) 0)

    (= (distance Cadiz Sevilla) 126)
    (= (distance Cadiz Malaga) 240)
    (= (distance Cadiz Madrid) 654)
    (= (distance Cadiz Jaen) 330)
    (= (distance Cadiz Huelva) 214)
    (= (distance Cadiz Granada) 296)
    (= (distance Cadiz Gibraltar) 124)
    (= (distance Cadiz Cordoba) 261)
    (= (distance Cadiz Bilbao) 1058)
    (= (distance Cadiz Almeria) 463)
    (= (distance Cadiz Barcelona) 1284)
    (= (distance Cadiz Cadiz) 0)

    (= (distance Cordoba Sevilla) 143)
    (= (distance Cordoba Malaga) 165)
    (= (distance Cordoba Madrid) 396)
    (= (distance Cordoba Jaen) 108)
    (= (distance Cordoba Huelva) 241)
    (= (distance Cordoba Granada) 160)
    (= (distance Cordoba Gibraltar) 294)
    (= (distance Cordoba Cadiz) 261)
    (= (distance Cordoba Bilbao) 796)
    (= (distance Cordoba Almeria) 316)
    (= (distance Cordoba Barcelona) 908)
    (= (distance Cordoba Cordoba) 0)

    (= (distance Gibraltar Sevilla) 201)
    (= (distance Gibraltar Malaga) 134)
    (= (distance Gibraltar Madrid) 662)
    (= (distance Gibraltar Jaen) 335)
    (= (distance Gibraltar Huelva) 289)
    (= (distance Gibraltar Granada) 255)
    (= (distance Gibraltar Cordoba) 294)
    (= (distance Gibraltar Cadiz) 124)
    (= (distance Gibraltar Bilbao) 1110)
    (= (distance Gibraltar Almeria) 339)
    (= (distance Gibraltar Barcelona) 1124)
    (= (distance Gibraltar Gibraltar) 0)

    (= (distance Granada Sevilla) 252)
    (= (distance Granada Malaga) 125)
    (= (distance Granada Madrid) 421)
    (= (distance Granada Jaen) 93)
    (= (distance Granada Huelva) 346)
    (= (distance Granada Gibraltar) 255)
    (= (distance Granada Cordoba) 160)
    (= (distance Granada Cadiz) 296)
    (= (distance Granada Bilbao) 829)
    (= (distance Granada Almeria) 162)
    (= (distance Granada Barcelona) 868)
    (= (distance Granada Granada) 0)

    (= (distance Huelva Sevilla) 95)
    (= (distance Huelva Malaga) 301)
    (= (distance Huelva Madrid) 591)
    (= (distance Huelva Jaen) 347)
    (= (distance Huelva Granada) 346)
    (= (distance Huelva Gibraltar) 289)
    (= (distance Huelva Cordoba) 241)
    (= (distance Huelva Cadiz) 214)
    (= (distance Huelva Bilbao) 939)
    (= (distance Huelva Almeria) 505)
    (= (distance Huelva Barcelona) 1140)
    (= (distance Huelva Huelva) 0)

    (= (distance Jaen Sevilla) 246)
    (= (distance Jaen Malaga) 203)
    (= (distance Jaen Madrid) 335)
    (= (distance Jaen Huelva) 347)
    (= (distance Jaen Granada) 93)
    (= (distance Jaen Gibraltar) 335)
    (= (distance Jaen Cordoba) 108)
    (= (distance Jaen Cadiz) 330)
    (= (distance Jaen Bilbao) 730)
    (= (distance Jaen Almeria) 220)
    (= (distance Jaen Barcelona) 804)
    (= (distance Jaen Jaen) 0)

    (= (distance Madrid Sevilla) 534)
    (= (distance Madrid Malaga) 532)
    (= (distance Madrid Jaen) 335)
    (= (distance Madrid Huelva) 591)
    (= (distance Madrid Granada) 421)
    (= (distance Madrid Gibraltar) 662)
    (= (distance Madrid Cordoba) 396)
    (= (distance Madrid Cadiz) 654)
    (= (distance Madrid Bilbao) 395)
    (= (distance Madrid Almeria) 547)
    (= (distance Madrid Barcelona) 621)
    (= (distance Madrid Madrid) 0)

    (= (distance Malaga Sevilla) 209)
    (= (distance Malaga Madrid) 532)
    (= (distance Malaga Jaen) 203)
    (= (distance Malaga Huelva) 301)
    (= (distance Malaga Granada) 125)
    (= (distance Malaga Gibraltar) 134)
    (= (distance Malaga Cordoba) 165)
    (= (distance Malaga Cadiz) 240)
    (= (distance Malaga Bilbao) 939)
    (= (distance Malaga Almeria) 207)
    (= (distance Malaga Barcelona) 997)
    (= (distance Malaga Malaga) 0)

    (= (distance Sevilla Malaga) 209)
    (= (distance Sevilla Madrid) 534)
    (= (distance Sevilla Jaen) 246)
    (= (distance Sevilla Huelva) 95)
    (= (distance Sevilla Granada) 252)
    (= (distance Sevilla Gibraltar) 201)
    (= (distance Sevilla Cordoba) 143)
    (= (distance Sevilla Cadiz) 126)
    (= (distance Sevilla Bilbao) 933)
    (= (distance Sevilla Almeria) 410)
    (= (distance Sevilla Barcelona) 1046)
    (= (distance Sevilla Sevilla) 0)

    (= (fuel a1) 1000)
    (= (fuel a2) 1000)
    (= (fuel a3) 1000)

    (= (slow-speed a1) 10)
    (= (fast-speed a1) 20)
    (= (slow-burn a1) 1)
    (= (fast-burn a1) 2)
    (= (slow-speed a2) 10)
    (= (fast-speed a2) 40)
    (= (slow-burn a2) 1)
    (= (fast-burn a2) 2)
    (= (slow-speed a3) 10)
    (= (fast-speed a3) 15)
    (= (slow-burn a3) 1)
    (= (fast-burn a3) 3)

    (= (capacity a1) 3000)
    (= (capacity a2) 3000)
    (= (capacity a3) 3000)

    (= (refuel-rate a1) 1)
    (= (refuel-rate a2) 1)
    (= (refuel-rate a3) 1)
    
    (= (total-fuel-used a1) 0)
    (= (total-fuel-used a2) 0)
    (= (total-fuel-used a3) 0)

    (= (boarding-time) 1)
    (= (debarking-time) 1)

    (= (capacidad-pasajeros a1) 5)
    (= (pasajeros a1) 0)
    (= (capacidad-pasajeros a2) 5)
    (= (pasajeros a2) 0)
    (= (capacidad-pasajeros a3) 5)
    (= (pasajeros a3) 0)

    (= (fuel-limit a1) 15000)
    (= (fuel-limit a2) 10000)
    (= (fuel-limit a3) 5000)

    (= (duration-limit a1) 500)
    (= (duration-limit a2) 500)
    (= (duration-limit a3) 500)

    (= (total-duration-used a1) 0)
    (= (total-duration-used a2) 0)
    (= (total-duration-used a3) 0)

    (destino p1 Madrid) 
    (destino p2 Madrid)
    (destino p3 Gibraltar) 
    (destino p4 Sevilla)
    (destino p5 Malaga)
    (destino p6 Jaen)
    (destino p7 Jaen)
    (destino p8 Granada)
    (destino p9 Bilbao)
    (destino p10 Huelva)
    (destino p11 Madrid)
    (destino p12 Madrid)
    (destino p13 Madrid)
    (destino p14 Sevilla)
    (destino p15 Gibraltar)
    (destino p16 Granada)
    (destino p17 Madrid)
    (destino p18 Sevilla)
    (destino p19 Sevilla)
    (destino p20 Cadiz)
    (destino p21 Huelva)
    (destino p22 Cadiz)
 )


(:tasks-goal
   :tasks(
   (transport-person p1 Madrid) 
   (transport-person p2 Madrid)
   (transport-person p3 Gibraltar) 
   (transport-person p4 Sevilla)
   (transport-person p5 Malaga)
   (transport-person p6 Jaen)
   (transport-person p7 Jaen)
   (transport-person p8 Granada)
   (transport-person p9 Bilbao)
   (transport-person p10 Huelva)
   (transport-person p11 Madrid)
   (transport-person p12 Madrid)
   (transport-person p13 Madrid)
   (transport-person p14 Sevilla)
   (transport-person p15 Gibraltar)
   (transport-person p16 Granada)
   (transport-person p17 Madrid)
   (transport-person p18 Sevilla)
   (transport-person p19 Sevilla)
   (transport-person p20 Cadiz)
   (transport-person p21 Huelva)
   (transport-person p22 Cadiz)
   )
  )
)
   
    
    
    

    
