(define (problem BELKAN)
    (:domain Ejercicio2)
  (:objects
        Princesa Principe Bruja Profesor Leonardo - character
        Oscar Manzana Rosa Algoritmo Oro Bikini Zapatillas - item
        Hacker - player
        z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 - zone
        Norte Sur Este Oeste - orientation
        Bosque Agua Precipicio Arena Piedra - type
  )
  (:init
        ; Conexiones entre zonas y su orientación
        (rute z1 z3 Este)
        (rute z1 z2 Sur)
        (rute z2 z1 Norte)
        (rute z2 z4 Este)
        (rute z2 z11 Sur)
        (rute z3 z1 Oeste)
        (rute z3 z4 Sur)
        (rute z3 z5 Este)
        (rute z4 z3 Norte)
        (rute z4 z2 Oeste)
        (rute z5 z3 Oeste)
        (rute z5 z7 Este)
        (rute z5 z6 Sur)
        (rute z6 z5 Norte)
        (rute z6 z15 Sur)
        (rute z7 z5 Oeste)
        (rute z7 z9 Este)
        (rute z7 z8 Sur)
        (rute z8 z7 Norte)
        (rute z8 z10 Este)
        (rute z8 z17 Sur)
        (rute z9 z7 Oeste)
        (rute z9 z10 Sur)
        (rute z10 z9 Norte)
        (rute z10 z8 Oeste)
        (rute z10 z19 Sur)
        (rute z11 z2 Norte)
        (rute z11 z13 Este)
        (rute z11 z12 Sur)
        (rute z12 z11 Norte)
        (rute z12 z14 Este)
        (rute z12 z21 Sur)
        (rute z13 z11 Oeste)
        (rute z13 z15 Este)
        (rute z14 z12 Oeste)
        (rute z14 z23 Sur)
        (rute z15 z6 Norte)
        (rute z15 z13 Oeste)
        (rute z15 z16 Sur)
        (rute z16 z15 Norte)
        (rute z16 z18 Este)
        (rute z16 z25 Sur)
        (rute z17 z8 Norte)
        (rute z17 z19 Este)
        (rute z18 z16 Oeste)
        (rute z18 z20 Este)
        (rute z19 z10 Norte)
        (rute z19 z17 Oeste)
        (rute z20 z18 Oeste)
        (rute z21 z12 Norte)
        (rute z21 z23 Este)
        (rute z22 z25 Oeste)
        (rute z22 z24 Este)
        (rute z23 z21 Oeste)
        (rute z23 z25 Este)
        (rute z24 z22 Oeste)
        (rute z25 z23 Oeste)
        (rute z25 z22 Este)

        ; Distancia entre las zonas
        (= (distance z1 z3) 1)
        (= (distance z1 z2) 2)
        (= (distance z2 z1) 2)
        (= (distance z2 z4) 3)
        (= (distance z2 z11) 4)
        (= (distance z3 z1) 1)
        (= (distance z3 z4) 5)
        (= (distance z3 z5) 1)
        (= (distance z4 z3) 5)
        (= (distance z4 z2) 3)
        (= (distance z5 z3) 1)
        (= (distance z5 z7) 2)
        (= (distance z5 z6) 3)
        (= (distance z6 z5) 3)
        (= (distance z6 z15) 4)
        (= (distance z7 z5) 2)
        (= (distance z7 z9) 5)
        (= (distance z7 z8) 1)
        (= (distance z8 z7) 1)
        (= (distance z8 z10) 2)
        (= (distance z8 z17) 3)
        (= (distance z9 z7) 5)
        (= (distance z9 z10) 4)
        (= (distance z10 z9) 4)
        (= (distance z10 z8) 2)
        (= (distance z10 z19) 5)
        (= (distance z11 z2) 4)
        (= (distance z11 z13) 1)
        (= (distance z11 z12) 2)
        (= (distance z12 z11) 2)
        (= (distance z12 z14) 3)
        (= (distance z12 z21) 4)
        (= (distance z13 z11) 1)
        (= (distance z13 z15) 5)
        (= (distance z14 z12) 3)
        (= (distance z14 z23) 1)
        (= (distance z15 z6) 4)
        (= (distance z15 z13) 5)
        (= (distance z15 z16) 2)
        (= (distance z15 z17) 1)
        (= (distance z16 z15) 2)
        (= (distance z16 z18) 3)
        (= (distance z16 z25) 4)
        (= (distance z17 z8) 3)
        (= (distance z17 z19) 5)
        (= (distance z17 z15) 1)
        (= (distance z18 z16) 3)
        (= (distance z18 z20) 1)
        (= (distance z19 z10) 5)
        (= (distance z19 z17) 5)
        (= (distance z19 z20) 2)
        (= (distance z20 z18) 1)
        (= (distance z20 z19) 2)
        (= (distance z21 z12) 4)
        (= (distance z21 z23) 2)
        (= (distance z22 z25) 3)
        (= (distance z22 z24) 4)
        (= (distance z23 z21) 2)
        (= (distance z23 z25) 5)
        (= (distance z23 z14) 1)
        (= (distance z24 z22) 4)
        (= (distance z25 z23) 5)
        (= (distance z25 z22) 3)
        (= (distance z25 z16) 4)

        ; Inicializo a 0 la distancia total a minimizar
        (= (total_distance) 0)

        ; Localización y orientación del jugador
        (location Hacker z1)
        (looking Hacker Sur)

        ; Localización de los personajes
        (location Princesa z4)
        (location Principe z18)
        (location Bruja z7)
        (location Profesor z10)
        (location Leonardo z11)

        ; Localización de los objetos
        (location Manzana z12)
        (location Oscar z16)
        (location Rosa z17)
        (location Oro z22)
        (location Algoritmo z6)
        (location Manzana z9)
        (location Oscar z8)
        (location Rosa z21)
        (location Oro z13)
        (location Algoritmo z2)

        ; Por defecto, no tienen ningún objeto ni jugador ni personajes
        (handempty Hacker)
        (handempty Hacker)
        (handempty Principe)
        (handempty Princesa)
        (handempty Bruja)
        (handempty Profesor)
        (handempty Leonardo)
  )

  (:goal (exists (?i1 ?i2 ?i3 ?i4 ?i5 - item) 
         (and (has Princesa ?i1)
              (has Principe ?i2)
              (has Bruja ?i3)
              (has Profesor ?i4)
              (has Leonardo ?i5)
          ))
  )
  (:metric minimize (total_distance))
)
